include:
  - remote: 'https://gitlab-templates.ddbuild.io/dd-package/v1/template.yml'
  - remote: 'https://gitlab-templates.ddbuild.io/slack-notifier/v1/template.yml'

stages:
- build-ci
- build
- validate
- make deb
- release
- notify

variables:
  CURRENT_IMAGE_VERSION: 1
  GIT_CLONE_PATH: $CI_BUILDS_DIR/docker/machine

build ci image:
  stage: build-ci
  tags: [ "runner:docker", "size:large" ]
  only:
    changes:
      - .gitlab-ci.yml
      - .gitlab-ci/**/*
    refs:
      - master
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  script:
    - docker build --tag 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/machine:$CURRENT_IMAGE_VERSION .gitlab-ci/docker
    - docker push 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/machine:$CURRENT_IMAGE_VERSION

.build_base:
  tags: [ "runner:docker", "size:large"  ]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/machine:$CURRENT_IMAGE_VERSION

build:
  extends: .build_base
  stage: build
  script:
    - make build
  after_script:
    - "[[ \"$(find bin -type f -name docker-machine*)\" != \"\" ]]"
  artifacts:
    paths:
      - bin/
    expire_in: 1 week

test:
  extends: .build_base
  stage: validate
  script:
    - make test

validate:
  extends: .build_base
  stage: validate
  script:
    - make validate

make deb:
  stage: make deb
  image: ubuntu:18.04
  tags: [ "runner:main", "size:large" ]
  variables:
    DEB_DIR: .gitlab-ci/deb/docker-machine
  script:
    - mkdir -p $DEB_DIR/usr/local/bin
    - cp -v bin/docker-machine* $DEB_DIR/usr/local/bin/
    - chmod -R 775 $DEB_DIR
    - 'echo "Version: $CI_PIPELINE_ID" >> $DEB_DIR/DEBIAN/control'
    - dpkg-deb --build $DEB_DIR
  after_script:
    - "[[ \"$(find $DEB_DIR -type f -name docker-machine*.deb)\" != \"\"  ]]"
  artifacts:
    paths:
      - .gitlab-ci/deb/docker-machine.deb
    expire_in: 1 week

upload deb:
  extends: .dd-package.upload-debian-package
  variables:
    DEB_PATH: ".gitlab-ci/deb/docker-machine.deb"

upload deb unstable:
  extends: .dd-package.upload-debian-package
  variables:
    DD_PACKAGE_REPO: binaries.ddbuild-unstable.io
    DEB_PATH: ".gitlab-ci/deb/docker-machine.deb"

on-failure:
  extends: .slack-notifier.on-failure
